### ISSUE TITLE
To update the name of menu item

### ISSUE THREAD

**Issue by hujinhui69** [dgoguerra/bootstrap-menu#1]
It's one of the best bootstrap context menu plugin-ins that I've been tested so far. Many features provided are very useful. E.g., isShown, isEnabled, etc. 

Sometimes, the name of the menu item needs to be updated with the context change. From what I understand, once menu is declared, the name of the action is rendered only once during init(), even action.name is changed later on, the view won't be updated accordingly. 

Right now, I change the code a little bit to accommodate my needs:

In prototype.open, I added 

```
        if(action.isShown && action.isShown(elemData)) { //added to reflect changes of menu item text
            var $name = $action.find('a').contents().last();
            var updateText = action.name;
            if(/^\s/.test($name.text())) { //keep the icon spacer
                updateText = ' ' + updateText;
            }
            $name.replaceWith(updateText); 
        }
```

as for where to change  the name of action, isShown is a good place to do that. 

I believe there are better ways to achieve this, hopefully more features will be added.

**Comment by dgoguerra** [comment]
Thanks for the feedback!

That looks like a nice feature, and very easy to implement. I'm going to release soon a new version to improve this, where optionally you can define the `name` attribute as a function that works the same way as `isShown`, `isEnabled`, etc. and returns the name to render each time the modal is opened.

**Comment by dgoguerra** [comment]
Done, make sure to use [v1.0.9](https://github.com/dgoguerra/bootstrap-menu/releases/tag/v1.0.9) onward.
