### ISSUE TITLE
Exception when clicking on divider

### ISSUE THREAD

**Issue by limsbeheer** [dgoguerra/bootstrap-menu#3]
Hi dgoguerra,

Thanks for the Bootstrap context-menu plugin, it integrates very nicely with Bootstrap styled websites.
Unfortunately, we found an issue when clicking on the divider. An exception is raised: 'Error: Unable to get property 'onClick' of undefined or null reference'.
(This can be easily fixed by adding if (actionId === undefined) return; at line 238).

Is it possible to fix this in the next release?
Thanks!

**Comment by dgoguerra** [comment]
Thanks! Fixed, published as v1.0.12.

**Comment by limsbeheer** [comment]
Thanks for the quick fix and update. Works great!
