### ISSUE TITLE
Cannot find module 'jquery-ui/position'

### ISSUE THREAD

**Issue by romosch** [dgoguerra/bootstrap-menu#6]
When requiring bootstrap-menu, I recently startet to get the error:
Uncaught Error: Cannot find module 'jquery-ui/position'

This happened overnight, and I noticed the only difference was that now, bootstrap-menu was installing jquery-ui@1.12.0, instead of the previous 1.10.5.

Indeed, manually removing the '^' from the jquery-ui dependency in the bootstrap-menu package.json file fixed the error. Could you add this fix so that this no longer happens on a fresh npm install? Or maybe leave it at that version in a previous release?

Cheers

**Comment by dgoguerra** [comment]
Hi, can you check if you have the latest version of bootstrap-menu (1.0.13)? Its updated to support the new versions of jquery and jquery-ui.

Thanks!
