### ISSUE TITLE
BootstrapMenu.min.js:1 Uncaught TypeError: Cannot read property 'onClick' of undefined

### ISSUE THREAD

**Issue by happymade** [dgoguerra/bootstrap-menu#7]
Step：
1、open demos.html,
2、Demo 1,Right click anywhere inside this box,
3、No Move Mouse !!! Now Click Mouse Left Button!!! ---> Error:BootstrapMenu.min.js:1 Uncaught TypeError: Cannot read property 'onClick' of undefined.（Chrome）

**Comment by dgoguerra** [comment]
Thanks! Fixed
