### ISSUE TITLE
If you have only one option in the menu and use isShown, the menu shows up as a small line if isShown return false

### ISSUE THREAD

**Issue by Leandro-Albano** [dgoguerra/bootstrap-menu#8]
If you have only one option in the menu and use isShown, the menu shows up as a small line if isShown return false.

I think, if there is no option, the menu shouldn't appear.

**Comment by dgoguerra** [comment]
I've added instead a 'No available actions' message when this happens (you can customize the message with a `noActionsMessage` option), I think its more clear than the menu not opening. Let me know if that solution doesn't work for you.

**Comment by Leandro-Albano** [comment]
That's awesome! I think the massage is better too. Thanks!
